In [7]:
import numpy as np
"""
%pip install gdown
%gdown 1iOdA7wG3kKk3OgPDSC4Z4014eCoCKV6C 
code to download the sudoku.csv file from google drive.
Code snippet to extract sudokus from file 'sudoku.csv'
https://www.kaggle.com/datasets/bryanpark/sudoku
"""

quizzes = np.zeros((1000000, 81), np.int32)
solutions = np.zeros((1000000, 81), np.int32)
for i, line in enumerate(open('sudoku copy.csv', 'r').read().splitlines()[1:]):
    quiz, solution = line.split(",")
    for j, q_s in enumerate(zip(quiz, solution)):
        q, s = q_s
        quizzes[i, j] = q
        solutions[i, j] = s
quizzes = quizzes.reshape((-1, 9, 9))
solutions = solutions.reshape((-1, 9, 9))


In [10]:
s = list([list(i) for i in quizzes[0]])


In [3]:
import sudoku


In [4]:
solver = sudoku.Sudoku(s, inter_change="row")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="column")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="square")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)

Generation 11 -Best candidate's fitness 0 -Worst candidate's fitness 6
CPU times: user 21.9 s, sys: 14.2 ms, total: 21.9 s
Wall time: 21.9 s
0
[[5 3 8 9 1 2 6 7 4]
 [8 6 7 3 9 5 2 1 4]
 [4 5 1 6 8 9 7 3 2]
 [3 7 2 1 6 4 8 5 9]
 [7 5 6 4 3 8 9 2 1]
 [1 9 5 2 7 3 4 8 6]
 [2 8 9 5 4 7 1 6 3]
 [6 2 4 8 5 1 3 9 7]
 [9 1 3 7 2 6 5 4 8]]
Generation 82 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 2min 27s, sys: 0 ns, total: 2min 27s
Wall time: 2min 27s
0
Generation 9 -Best candidate's fitness 0 -Worst candidate's fitness 8
CPU times: user 23.3 s, sys: 3.76 ms, total: 23.3 s
Wall time: 23.3 s
0


In [12]:
s = list([list(i) for i in quizzes[1]])
solver = sudoku.Sudoku(s, inter_change="row")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="column")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="square")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)

[[6 4 2 1 7 9 3 5 8]
 [1 8 7 5 4 3 9 6 2]
 [5 2 9 7 1 8 4 3 6]
 [9 6 8 4 3 5 2 1 7]
 [3 1 4 9 2 6 8 7 5]
 [8 7 3 4 5 1 6 2 9]
 [7 9 1 8 6 2 5 4 3]
 [6 3 5 2 8 4 7 9 1]
 [2 5 6 3 9 7 1 8 4]]
Generation 78 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 2min 53s, sys: 59.8 ms, total: 2min 53s
Wall time: 2min 53s
0
Generation 14 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 34.4 s, sys: 0 ns, total: 34.4 s
Wall time: 34.4 s
0
Generation 11 -Best candidate's fitness 0 -Worst candidate's fitness 5
CPU times: user 28.2 s, sys: 0 ns, total: 28.2 s
Wall time: 28.2 s
0


In [13]:
s = list([list(i) for i in quizzes[1]])
solver = sudoku.Sudoku(s, inter_change="row")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="column")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="square")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)

[[3 4 6 1 7 9 2 5 8]
 [1 8 7 2 4 3 9 6 5]
 [5 2 9 3 1 8 4 7 6]
 [9 6 4 8 2 5 3 1 7]
 [4 1 5 9 3 6 8 7 2]
 [8 7 3 4 5 1 6 2 9]
 [7 9 1 8 6 2 5 4 3]
 [6 3 2 5 8 4 7 9 1]
 [2 5 8 6 9 7 1 3 4]]
CPU times: user 3min 42s, sys: 0 ns, total: 3min 42s
Wall time: 3min 42s
2
Generation 16 -Best candidate's fitness 0 -Worst candidate's fitness 3
CPU times: user 39.9 s, sys: 9.88 ms, total: 39.9 s
Wall time: 39.9 s
0
Generation 10 -Best candidate's fitness 0 -Worst candidate's fitness 6
CPU times: user 26.5 s, sys: 0 ns, total: 26.5 s
Wall time: 26.5 s
0


In [14]:
s = list([list(i) for i in quizzes[2]])
solver = sudoku.Sudoku(s, inter_change="row")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="column")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="square")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)

[[6 9 5 1 2 7 3 8 4]
 [1 3 8 4 5 9 6 7 2]
 [7 2 1 3 9 6 8 4 5]
 [8 5 1 2 6 4 9 3 7]
 [4 7 3 9 8 2 5 1 6]
 [9 4 6 5 1 3 7 2 8]
 [3 1 7 6 4 8 2 5 9]
 [2 8 9 7 3 5 4 6 1]
 [5 6 2 8 7 4 1 9 3]]
CPU times: user 3min 48s, sys: 20 ms, total: 3min 48s
Wall time: 3min 48s
2
Generation 16 -Best candidate's fitness 0 -Worst candidate's fitness 2
CPU times: user 43.8 s, sys: 10 ms, total: 43.8 s
Wall time: 43.8 s
0
Generation 11 -Best candidate's fitness 0 -Worst candidate's fitness 6
CPU times: user 28.9 s, sys: 0 ns, total: 28.9 s
Wall time: 28.9 s
0


In [15]:
s = list([list(i) for i in quizzes[3]])
solver = sudoku.Sudoku(s, inter_change="row")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="column")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="square")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)

Generation 11 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 31.1 s, sys: 10 ms, total: 31.1 s
Wall time: 31.1 s
0
Generation 14 -Best candidate's fitness 0 -Worst candidate's fitness 2
CPU times: user 35.4 s, sys: 4 µs, total: 35.4 s
Wall time: 35.4 s
0
Generation 12 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 30.8 s, sys: 0 ns, total: 30.8 s
Wall time: 30.8 s
0


In [16]:
s = list([list(i) for i in quizzes[4]])
solver = sudoku.Sudoku(s, inter_change="row")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="column")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="square")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)

Generation 30 -Best candidate's fitness 0 -Worst candidate's fitness 2
CPU times: user 1min 8s, sys: 20 ms, total: 1min 8s
Wall time: 1min 8s
0
[[2 7 3 9 5 1 4 6 8]
 [7 5 2 3 6 8 1 4 9]
 [5 9 7 8 4 6 2 3 1]
 [9 4 5 7 8 2 3 1 6]
 [1 9 4 6 2 3 8 5 7]
 [6 3 8 4 1 7 9 2 5]
 [3 8 1 2 9 5 6 7 4]
 [4 6 9 5 3 1 7 8 2]
 [8 2 6 1 7 4 5 9 3]]
Generation 85 -Best candidate's fitness 0 -Worst candidate's fitness 2
CPU times: user 3min 14s, sys: 0 ns, total: 3min 14s
Wall time: 3min 14s
0
Generation 12 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 31.5 s, sys: 20 ms, total: 31.6 s
Wall time: 31.6 s
0


In [17]:
s = list([list(i) for i in quizzes[5]])
solver = sudoku.Sudoku(s, inter_change="row")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="column")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="square")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)

Generation 17 -Best candidate's fitness 0 -Worst candidate's fitness 3
CPU times: user 40.9 s, sys: 1.18 ms, total: 40.9 s
Wall time: 40.9 s
0
[[1 3 6 8 5 4 2 9 7]
 [3 8 7 2 4 6 1 5 9]
 [6 2 3 4 1 9 5 7 8]
 [4 9 2 3 7 5 8 6 1]
 [8 1 5 9 6 7 3 2 4]
 [5 4 7 1 3 2 9 8 6]
 [2 5 4 6 9 8 7 1 3]
 [9 1 8 7 2 3 6 4 5]
 [7 6 9 5 8 1 4 3 2]]
CPU times: user 3min 43s, sys: 0 ns, total: 3min 43s
Wall time: 3min 43s
2
Generation 11 -Best candidate's fitness 0 -Worst candidate's fitness 6
CPU times: user 28.1 s, sys: 0 ns, total: 28.1 s
Wall time: 28.1 s
0


In [18]:
s = list([list(i) for i in quizzes[6]])
solver = sudoku.Sudoku(s, inter_change="row")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="column")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
solver = sudoku.Sudoku(s, inter_change="square")
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)

[[2 8 9 7 6 5 4 3 1]
 [9 4 7 6 3 2 8 1 5]
 [6 9 5 1 7 8 3 2 4]
 [6 1 3 8 9 4 7 5 2]
 [5 7 1 4 2 3 9 6 8]
 [8 2 4 9 5 6 1 7 3]
 [4 3 2 5 1 9 6 8 7]
 [1 5 6 3 8 7 2 4 9]
 [3 7 8 2 4 1 5 9 6]]
CPU times: user 3min 43s, sys: 0 ns, total: 3min 43s
Wall time: 3min 43s
2
[[2 9 6 1 5 8 4 7 3]
 [8 1 4 6 2 9 3 5 7]
 [9 7 5 3 1 4 2 6 8]
 [7 6 1 8 4 3 5 9 2]
 [6 5 3 9 7 2 1 8 4]
 [5 2 8 4 3 6 9 7 1]
 [4 8 7 2 9 1 6 3 5]
 [3 4 2 5 6 7 8 1 9]
 [1 3 9 2 8 5 7 4 6]]
Generation 82 -Best candidate's fitness 0 -Worst candidate's fitness 2
CPU times: user 3min 6s, sys: 30 ms, total: 3min 6s
Wall time: 3min 6s
0
Generation 11 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 28.6 s, sys: 0 ns, total: 28.6 s
Wall time: 28.6 s
0
