In [1]:
import numpy as np
"""
%pip install gdown
%gdown 1iOdA7wG3kKk3OgPDSC4Z4014eCoCKV6C 
code to download the sudoku.csv file from google drive.
Code snippet to extract sudokus from file 'sudoku.csv'
https://www.kaggle.com/datasets/bryanpark/sudoku
"""

quizzes = np.zeros((1000000, 81), np.int32)
solutions = np.zeros((1000000, 81), np.int32)
for i, line in enumerate(open('sudoku copy.csv', 'r').read().splitlines()[1:]):
    quiz, solution = line.split(",")
    for j, q_s in enumerate(zip(quiz, solution)):
        q, s = q_s
        quizzes[i, j] = q
        solutions[i, j] = s
quizzes = quizzes.reshape((-1, 9, 9))
solutions = solutions.reshape((-1, 9, 9))
s = list([list(i) for i in quizzes[0]])


In [2]:
s = [[0, 0, 4, 3, 0, 0, 2, 0, 9],
     [0, 0, 5, 0, 0, 9, 0, 0, 1],
     [0, 7, 0, 0, 6, 0, 0, 4, 3],
     [0, 0, 6, 0, 0, 2, 0, 8, 7],
     [1, 9, 0, 0, 0, 7, 4, 0, 0],
     [0, 5, 0, 0, 8, 3, 0, 0, 0],
     [6, 0, 0, 0, 0, 0, 1, 0, 5],
     [0, 0, 3, 5, 0, 8, 6, 9, 0],
     [0, 4, 2, 9, 1, 0, 3, 0, 0]]

In [3]:
import sudoku
solver = sudoku.Sudoku(s)

In [4]:
%time sol, ftns, ftns_history = solver.solve(cross_over="best candidate")
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="one-point cross-over")
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="insertion")
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="swap")
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random")
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random-pairs")
print(ftns)

CPU times: user 5min 3s, sys: 50.4 ms, total: 5min 3s
Wall time: 5min 3s
2
CPU times: user 4min 4s, sys: 90.1 ms, total: 4min 4s
Wall time: 4min 4s
4
CPU times: user 4min 17s, sys: 48 µs, total: 4min 17s
Wall time: 4min 17s
8
CPU times: user 4min 19s, sys: 10 ms, total: 4min 19s
Wall time: 4min 19s
8
[[1 6 4 2 3 5 9 7 8]
 [3 5 2 4 7 9 1 6 8]
 [2 6 9 8 7 1 5 4 3]
 [4 7 6 1 9 8 3 5 2]
 [1 9 2 6 5 7 4 8 3]
 [3 8 7 4 5 2 9 1 6]
 [6 9 8 7 1 3 5 4 2]
 [2 3 6 5 7 8 9 1 4]
 [1 4 5 6 9 2 3 7 8]]
CPU times: user 4min 51s, sys: 40 ms, total: 4min 51s
Wall time: 4min 51s
24
CPU times: user 4min 23s, sys: 14 µs, total: 4min 23s
Wall time: 4min 23s
24


In [5]:
sr = 0.6
%time sol, ftns, ftns_history = solver.solve(cross_over="best candidate", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="one-point cross-over", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="insertion", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="swap", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random-pairs", selection_rate=sr)
print(ftns)

Generation 47 -Best candidate's fitness 0 -Worst candidate's fitness 8
CPU times: user 2min 40s, sys: 10 ms, total: 2min 40s
Wall time: 2min 40s
0
Generation 47 -Best candidate's fitness 0 -Worst candidate's fitness 13
CPU times: user 2min 7s, sys: 10 ms, total: 2min 7s
Wall time: 2min 7s
0
Generation 60 -Best candidate's fitness 0 -Worst candidate's fitness 11
CPU times: user 2min 38s, sys: 10 ms, total: 2min 38s
Wall time: 2min 38s
0
Generation 55 -Best candidate's fitness 0 -Worst candidate's fitness 12
CPU times: user 2min 23s, sys: 10 ms, total: 2min 23s
Wall time: 2min 23s
0
[[1 8 4 2 3 5 6 7 9]
 [3 7 5 1 8 9 4 6 2]
 [2 6 9 8 7 1 5 4 3]
 [3 2 6 1 9 8 4 5 7]
 [1 5 2 6 4 7 9 8 3]
 [9 8 7 4 3 2 1 5 6]
 [6 5 1 9 8 3 7 4 2]
 [7 3 4 5 2 8 9 1 6]
 [1 2 5 6 9 4 3 8 7]]
CPU times: user 5min 1s, sys: 30 ms, total: 5min 1s
Wall time: 5min 1s
25
[[6 9 4 3 2 5 8 7 1]
 [3 8 1 7 4 9 2 6 5]
 [2 7 9 8 6 1 5 4 3]
 [3 8 6 1 9 7 4 5 2]
 [9 4 2 6 5 7 1 8 3]
 [9 8 7 4 2 3 5 1 6]
 [6 8 9 7 1 3 5 4 2]
 

In [6]:
sr = 0.4
%time sol, ftns, ftns_history = solver.solve(cross_over="best candidate", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="one-point cross-over", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="insertion", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="swap", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random-pairs", selection_rate=sr)
print(ftns)

Generation 23 -Best candidate's fitness 0 -Worst candidate's fitness 10
CPU times: user 1min 37s, sys: 4 µs, total: 1min 37s
Wall time: 1min 37s
0
Generation 28 -Best candidate's fitness 0 -Worst candidate's fitness 10
CPU times: user 1min 16s, sys: 20 ms, total: 1min 16s
Wall time: 1min 16s
0
Generation 34 -Best candidate's fitness 0 -Worst candidate's fitness 8
CPU times: user 1min 33s, sys: 0 ns, total: 1min 33s
Wall time: 1min 33s
0
Generation 34 -Best candidate's fitness 0 -Worst candidate's fitness 9
CPU times: user 1min 31s, sys: 10 ms, total: 1min 31s
Wall time: 1min 31s
0
[[6 9 4 3 2 5 1 7 8]
 [3 1 8 4 7 9 2 6 5]
 [2 5 9 8 6 1 7 4 3]
 [7 3 6 1 9 8 2 5 4]
 [4 9 2 6 5 7 1 8 3]
 [5 8 7 4 6 3 9 2 1]
 [6 8 1 7 9 3 5 4 2]
 [7 3 4 5 2 8 9 1 6]
 [1 2 5 6 9 4 3 7 8]]
CPU times: user 5min 29s, sys: 50 ms, total: 5min 29s
Wall time: 5min 29s
23
[[8 6 4 3 1 5 9 7 2]
 [3 4 1 7 8 9 2 6 5]
 [2 5 9 6 8 1 7 4 3]
 [3 2 6 1 9 8 4 5 7]
 [1 4 2 5 9 7 6 8 3]
 [5 8 7 4 3 6 9 2 1]
 [6 9 7 8 1 3 5 4 2

In [7]:
sr = 0.2
%time sol, ftns, ftns_history = solver.solve(cross_over="best candidate", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="one-point cross-over", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="insertion", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="swap", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random", selection_rate=sr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random-pairs", selection_rate=sr)
print(ftns)

Generation 18 -Best candidate's fitness 0 -Worst candidate's fitness 5
CPU times: user 1min 27s, sys: 10 ms, total: 1min 27s
Wall time: 1min 27s
0
Generation 16 -Best candidate's fitness 0 -Worst candidate's fitness 6
CPU times: user 47 s, sys: 1 µs, total: 47 s
Wall time: 47 s
0
Generation 16 -Best candidate's fitness 0 -Worst candidate's fitness 8
CPU times: user 46.2 s, sys: 10 ms, total: 46.2 s
Wall time: 46.2 s
0
Generation 17 -Best candidate's fitness 0 -Worst candidate's fitness 8
CPU times: user 49.4 s, sys: 0 ns, total: 49.4 s
Wall time: 49.4 s
0
[[1 8 4 3 6 5 2 7 9]
 [3 7 5 2 4 9 8 6 1]
 [2 6 9 8 7 1 5 4 3]
 [3 4 6 1 9 8 2 5 7]
 [5 4 2 9 6 7 1 8 3]
 [9 8 7 4 2 5 6 1 3]
 [6 8 5 7 1 3 9 4 2]
 [4 3 7 5 2 8 9 1 6]
 [1 2 5 6 9 4 3 7 8]]
CPU times: user 6min 3s, sys: 70 ms, total: 6min 3s
Wall time: 6min 3s
25
Generation 80 -Best candidate's fitness 0 -Worst candidate's fitness 11
CPU times: user 4min 58s, sys: 70 ms, total: 4min 58s
Wall time: 4min 58s
0


In [8]:
mr = 0.2
%time sol, ftns, ftns_history = solver.solve(cross_over="best candidate", mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="one-point cross-over", mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="insertion", mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="swap", mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random", mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random-pairs", mutation_rate=mr)
print(ftns)

CPU times: user 5min 1s, sys: 3 µs, total: 5min 1s
Wall time: 5min 1s
4
CPU times: user 4min 4s, sys: 10 ms, total: 4min 4s
Wall time: 4min 4s
4
CPU times: user 4min 10s, sys: 2 µs, total: 4min 10s
Wall time: 4min 10s
6
CPU times: user 4min 7s, sys: 2 µs, total: 4min 7s
Wall time: 4min 7s
4
[[8 1 4 6 2 5 3 7 9]
 [3 1 7 8 5 9 2 6 4]
 [2 5 9 7 6 1 8 4 3]
 [4 3 6 1 9 8 2 5 7]
 [1 5 2 9 6 7 4 8 3]
 [9 8 7 4 1 3 5 2 6]
 [6 8 9 7 1 3 5 4 2]
 [7 4 6 5 2 8 9 1 3]
 [1 2 5 6 9 4 3 8 7]]
CPU times: user 4min 29s, sys: 90 ms, total: 4min 30s
Wall time: 4min 30s
27
[[3 8 4 2 6 5 9 7 1]
 [3 7 1 8 4 9 2 6 5]
 [2 5 9 8 7 1 6 4 3]
 [7 3 6 1 9 8 4 5 2]
 [1 9 2 5 6 7 4 8 3]
 [5 8 7 4 2 3 1 9 6]
 [6 8 7 5 9 3 1 4 2]
 [4 2 3 5 7 8 9 1 6]
 [1 4 5 6 9 2 3 7 8]]
CPU times: user 4min 22s, sys: 10 ms, total: 4min 22s
Wall time: 4min 22s
25


In [9]:
mr = 0.6
%time sol, ftns, ftns_history = solver.solve(cross_over="best candidate", mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="one-point cross-over", mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="insertion", mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="swap", mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random", mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random-pairs", mutation_rate=mr)
print(ftns)

CPU times: user 4min 39s, sys: 10 ms, total: 4min 39s
Wall time: 4min 39s
2
CPU times: user 4min 6s, sys: 10 ms, total: 4min 6s
Wall time: 4min 6s
6
CPU times: user 4min 20s, sys: 2 µs, total: 4min 20s
Wall time: 4min 20s
9
CPU times: user 4min 2s, sys: 60 ms, total: 4min 2s
Wall time: 4min 2s
6
[[1 3 4 6 2 5 8 7 9]
 [3 8 5 7 1 9 4 6 2]
 [2 6 9 7 8 1 5 4 3]
 [3 4 6 1 9 8 2 5 7]
 [6 1 2 5 9 7 4 8 3]
 [9 8 7 4 2 5 3 1 6]
 [6 8 1 7 9 3 5 4 2]
 [2 3 7 5 4 8 9 1 6]
 [1 4 5 6 9 2 3 7 8]]
CPU times: user 4min 32s, sys: 20 ms, total: 4min 32s
Wall time: 4min 32s
23
CPU times: user 4min 36s, sys: 90 ms, total: 4min 36s
Wall time: 4min 36s
23


In [10]:
rp = 0.2
%time sol, ftns, ftns_history = solver.solve(cross_over="best candidate", random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="one-point cross-over", random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="insertion", random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="swap", random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random", random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random-pairs", random_proportion=rp)
print(ftns)

Generation 61 -Best candidate's fitness 0 -Worst candidate's fitness 12
CPU times: user 3min 24s, sys: 60 ms, total: 3min 24s
Wall time: 3min 24s
0
Generation 73 -Best candidate's fitness 0 -Worst candidate's fitness 15
CPU times: user 3min 1s, sys: 2 µs, total: 3min 1s
Wall time: 3min 1s
0
Generation 90 -Best candidate's fitness 0 -Worst candidate's fitness 12
CPU times: user 3min 43s, sys: 70 ms, total: 3min 43s
Wall time: 3min 43s
0
Generation 83 -Best candidate's fitness 0 -Worst candidate's fitness 14
CPU times: user 3min 25s, sys: 0 ns, total: 3min 25s
Wall time: 3min 25s
0
CPU times: user 4min 43s, sys: 0 ns, total: 4min 43s
Wall time: 4min 43s
25
[[3 6 4 8 2 5 9 7 1]
 [3 7 5 2 4 9 8 6 1]
 [2 8 9 7 6 1 5 4 3]
 [3 8 6 1 9 2 4 5 7]
 [4 6 2 5 9 7 1 8 3]
 [1 8 7 4 3 6 9 5 2]
 [6 9 1 7 5 3 8 4 2]
 [7 4 3 5 2 8 9 1 6]
 [1 2 5 6 9 8 3 7 4]]
CPU times: user 4min 53s, sys: 10 ms, total: 4min 53s
Wall time: 4min 53s
25


In [11]:
sr = 0.2
rp = 0.2
%time sol, ftns, ftns_history = solver.solve(cross_over="best candidate", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="one-point cross-over", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="insertion", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="swap", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random-pairs", selection_rate=sr, random_proportion=rp)
print(ftns)

Generation 14 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 1min 19s, sys: 2 µs, total: 1min 19s
Wall time: 1min 19s
0
Generation 14 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 37.3 s, sys: 0 ns, total: 37.3 s
Wall time: 37.3 s
0
Generation 13 -Best candidate's fitness 0 -Worst candidate's fitness 8
CPU times: user 35.1 s, sys: 0 ns, total: 35.1 s
Wall time: 35.1 s
0
Generation 15 -Best candidate's fitness 0 -Worst candidate's fitness 6
CPU times: user 39.1 s, sys: 10 ms, total: 39.1 s
Wall time: 39.1 s
0
[[1 3 4 2 6 5 8 7 9]
 [3 5 7 8 4 9 2 6 1]
 [2 7 9 8 6 1 5 4 3]
 [3 2 6 1 9 8 7 5 4]
 [5 1 2 4 9 7 6 8 3]
 [3 8 7 4 5 6 1 9 2]
 [6 7 9 1 8 3 5 4 2]
 [3 7 4 5 2 8 9 1 6]
 [1 2 5 6 9 8 3 7 4]]
CPU times: user 6min 57s, sys: 50 ms, total: 6min 57s
Wall time: 6min 57s
23
Generation 45 -Best candidate's fitness 0 -Worst candidate's fitness 13
CPU times: user 3min 8s, sys: 40 ms, total: 3min 9s
Wall time: 3min 9s
0


In [12]:
sr = 0.1
rp = 0.1
%time sol, ftns, ftns_history = solver.solve(cross_over="best candidate", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="one-point cross-over", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="insertion", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="swap", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random-pairs", selection_rate=sr, random_proportion=rp)
print(ftns)

Generation 11 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 1min 15s, sys: 0 ns, total: 1min 15s
Wall time: 1min 15s
0
Generation 9 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 26.5 s, sys: 0 ns, total: 26.5 s
Wall time: 26.5 s
0
Generation 9 -Best candidate's fitness 0 -Worst candidate's fitness 8
CPU times: user 26.6 s, sys: 1 µs, total: 26.6 s
Wall time: 26.6 s
0
Generation 10 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 28.5 s, sys: 9.48 ms, total: 28.5 s
Wall time: 28.5 s
0
[[3 1 4 6 2 5 8 7 9]
 [3 7 5 8 4 9 1 6 2]
 [2 6 9 7 5 1 8 4 3]
 [2 3 6 1 9 8 4 5 7]
 [6 5 2 4 9 7 1 8 3]
 [9 8 7 4 2 6 5 1 3]
 [6 8 7 1 9 3 5 4 2]
 [7 3 4 5 2 8 9 1 6]
 [1 7 5 6 9 8 3 2 4]]
CPU times: user 7min 26s, sys: 70 ms, total: 7min 26s
Wall time: 7min 26s
25
Generation 22 -Best candidate's fitness 0 -Worst candidate's fitness 8
CPU times: user 1min 42s, sys: 20 ms, total: 1min 42s
Wall time: 1min 42s
0


In [13]:
sr = 0.05
rp = 0.05
%time sol, ftns, ftns_history = solver.solve(cross_over="best candidate", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="one-point cross-over", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="insertion", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="swap", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random", selection_rate=sr, random_proportion=rp)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random-pairs", selection_rate=sr, random_proportion=rp)
print(ftns)

Generation 9 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 1min 4s, sys: 10 ms, total: 1min 4s
Wall time: 1min 4s
0
Generation 10 -Best candidate's fitness 0 -Worst candidate's fitness 2
CPU times: user 31 s, sys: 30 ms, total: 31.1 s
Wall time: 31.1 s
0
Generation 12 -Best candidate's fitness 0 -Worst candidate's fitness 2
CPU times: user 36.9 s, sys: 2 µs, total: 36.9 s
Wall time: 36.9 s
0
Generation 10 -Best candidate's fitness 0 -Worst candidate's fitness 2
CPU times: user 30.4 s, sys: 0 ns, total: 30.4 s
Wall time: 30.4 s
0
CPU times: user 7min 32s, sys: 130 ms, total: 7min 32s
Wall time: 7min 32s
25
Generation 16 -Best candidate's fitness 0 -Worst candidate's fitness 6
CPU times: user 1min 11s, sys: 10 ms, total: 1min 11s
Wall time: 1min 11s
0


In [14]:
sr = 0.1
rp = 0.1
mr = 0.6
%time sol, ftns, ftns_history = solver.solve(cross_over="best candidate", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="one-point cross-over", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="insertion", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="swap", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random-pairs", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)

Generation 11 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 1min 11s, sys: 2 µs, total: 1min 11s
Wall time: 1min 11s
0
Generation 9 -Best candidate's fitness 0 -Worst candidate's fitness 5
CPU times: user 25.3 s, sys: 0 ns, total: 25.3 s
Wall time: 25.3 s
0
Generation 10 -Best candidate's fitness 0 -Worst candidate's fitness 6
CPU times: user 27.5 s, sys: 0 ns, total: 27.5 s
Wall time: 27.5 s
0
Generation 9 -Best candidate's fitness 0 -Worst candidate's fitness 6
CPU times: user 24.6 s, sys: 20 ms, total: 24.7 s
Wall time: 24.6 s
0
[[8 3 4 1 2 5 9 7 6]
 [3 7 1 2 4 9 8 6 5]
 [2 6 9 8 5 1 7 4 3]
 [3 2 6 1 9 8 7 5 4]
 [1 9 2 5 4 7 6 8 3]
 [5 8 7 4 3 6 9 1 2]
 [6 7 9 8 1 3 5 4 2]
 [2 3 4 5 7 8 9 1 6]
 [1 2 5 6 9 7 3 4 8]]
CPU times: user 7min 16s, sys: 30 ms, total: 7min 17s
Wall time: 7min 17s
26
Generation 26 -Best candidate's fitness 0 -Worst candidate's fitness 10
CPU times: user 1min 51s, sys: 10 ms, total: 1min 51s
Wall time: 1min 51s
0


In [4]:
sr = 0.2
rp = 0.2
mr = 0.8
%time sol, ftns, ftns_history = solver.solve(cross_over="best candidate", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="one-point cross-over", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="insertion", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="swap", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random-pairs", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)

Generation 12 -Best candidate's fitness 0 -Worst candidate's fitness 8
CPU times: user 1min 25s, sys: 0 ns, total: 1min 25s
Wall time: 1min 25s
0
Generation 16 -Best candidate's fitness 0 -Worst candidate's fitness 6
CPU times: user 53.7 s, sys: 9.98 ms, total: 53.7 s
Wall time: 53.7 s
0
Generation 14 -Best candidate's fitness 0 -Worst candidate's fitness 9
CPU times: user 46.7 s, sys: 20 ms, total: 46.7 s
Wall time: 46.7 s
0
Generation 15 -Best candidate's fitness 0 -Worst candidate's fitness 8
CPU times: user 48.8 s, sys: 0 ns, total: 48.8 s
Wall time: 48.8 s
0
Generation 59 -Best candidate's fitness 0 -Worst candidate's fitness 12
CPU times: user 4min 36s, sys: 120 ms, total: 4min 36s
Wall time: 4min 36s
0


In [5]:
sr = 0.1
rp = 0.3
mr = 0.2
%time sol, ftns, ftns_history = solver.solve(cross_over="best candidate", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="one-point cross-over", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="insertion", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="swap", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random-pairs", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)

Generation 12 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 1min 27s, sys: 0 ns, total: 1min 27s
Wall time: 1min 27s
0
Generation 10 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 37.1 s, sys: 0 ns, total: 37.1 s
Wall time: 37.1 s
0
Generation 13 -Best candidate's fitness 0 -Worst candidate's fitness 4
CPU times: user 47.5 s, sys: 10 ms, total: 47.5 s
Wall time: 47.5 s
0
Generation 13 -Best candidate's fitness 0 -Worst candidate's fitness 2
CPU times: user 46.1 s, sys: 10 ms, total: 46.1 s
Wall time: 46.1 s
0
[[8 6 4 2 3 5 9 7 1]
 [3 7 1 8 4 9 2 6 5]
 [2 5 9 7 6 1 8 4 3]
 [3 2 6 1 9 8 4 5 7]
 [1 9 2 6 5 7 4 8 3]
 [5 8 7 4 3 2 9 1 6]
 [6 8 9 7 1 3 5 4 2]
 [7 3 4 5 2 8 9 1 6]
 [1 2 5 6 9 4 3 7 8]]
CPU times: user 8min 13s, sys: 250 ms, total: 8min 13s
Wall time: 8min 13s
13


In [4]:
sr = 0.1
rp = 0.1
mr = 0.8
%time sol, ftns, ftns_history = solver.solve(cross_over="best candidate", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="one-point cross-over", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="insertion", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="swap", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)
%time sol, ftns, ftns_history = solver.solve(cross_over="matrix-random-pairs", selection_rate=sr, random_proportion=rp, mutation_rate=mr)
print(ftns)

Generation 10 -Best candidate's fitness 0 -Worst candidate's fitness 6
CPU times: user 1min 7s, sys: 0 ns, total: 1min 7s
Wall time: 1min 7s
0
Generation 10 -Best candidate's fitness 0 -Worst candidate's fitness 6
CPU times: user 28.1 s, sys: 31.2 ms, total: 28.2 s
Wall time: 28.2 s
0
Generation 9 -Best candidate's fitness 0 -Worst candidate's fitness 8
CPU times: user 25.8 s, sys: 9.85 ms, total: 25.8 s
Wall time: 25.8 s
0
Generation 11 -Best candidate's fitness 0 -Worst candidate's fitness 6
CPU times: user 30.2 s, sys: 9.9 ms, total: 30.2 s
Wall time: 30.2 s
0
Generation 27 -Best candidate's fitness 0 -Worst candidate's fitness 8
CPU times: user 1min 56s, sys: 79.8 ms, total: 1min 56s
Wall time: 1min 56s
0


# Genetic Algorithm

In [ ]:
def transform(problem_grid: List[List]) -> List[List]:
    """
    Transforms the problem_grid passed, testing the sudoku has three main comparisons.
      Assuming we have an untransformed grid, we have:
        1. All rows must have each number from 1 to 9 with no repetition
        2. All columns must have each number from 1 to 9 wtih no repetition
        3. All 3x3 squares must have each number from 1 to 9 with no repetition
      These last conditions are assuming we have a 9x9 grid with 81 numbers in total. 

      To be able to easily check for rows, columns and squares, we transform the grid, to convert each 3x3 square to a 1x9 row. 
      These way in the untransformed version we check rows and columns
      In the transformed version we check rows, and now we have checked every condition.
    Parameters:
      - problem_grid (list): Sudoku grid (Transformed or Untransformed).
    Returns (list).
      - transformed grid .
          If problem_grid is the original sudoku it converts it
          If the problem_grid is the already transformed sudoku, it unrolls it
    """
    file_lines = problem_grid
    problem_grid = [[] for i in range(len(file_lines))] #Empty grid
    sqrt_n = 3 # this parameter could change if one wants to generalize for sudokus of other dimensions
    for j in range(len(file_lines)): 
        line_values = [(int(value) if value != 0 else None) for value in file_lines[j]]
        for i in range(len(line_values)):
            problem_grid[
                int(i / sqrt_n) +
                int(j / sqrt_n) * sqrt_n
                ].append(line_values[i])
        
    return problem_grid

In [ ]:
def solve(problem_grid: List[List],
          population_size: Optional[int] = 10000,
          selection_rate: Optional[float] = 0.8,
          max_generations_count: Optional[int] = 100,
          mutation_rate: Optional[float] = 0.4,
          random_proportion: Optional[float] = 0.5,
          verbose: Optional[bool] = False,
          ):
    """
    Solves a Sudoku puzzle using a genetic algorithm.
    It receives a problem grid written in different lines (Not one line with 81 numbers) and in the empty spaces, a 0 should appear
    In the "reading sudoku" chapter there is an example of how the initial sudoku should be formatted.

    Parameters:
        - problem_grid (list): An 9x9 sudoku grid.
        - population_size (int): The initial population size.
        - selection_rate (int)
        - max_generations_count (int)
        - mutation_rate (int)
      Returns:
        - population[0] (list): Solved sudoku.
        - best_fitness (int): last best_fitness, when not solved in the max_generations it gets the last one.
        - fitness_history (list): For plotting progress of learning
    """
    
    problem_grid = transform(problem_grid)
    
    def empty_grid(elem_generator: List[List] | None = None) -> List[List]:
        """
        Returns an empty Sudoku grid.
        Parameters:
        - elem_generator (function) (optional=None): Is is used to generate initial values of the grid's elements.
              If it's not given, all grid's elements will be "None".
        """
        return [
            [
                (None if elem_generator is None else elem_generator(i, j))
                for j in range(len(problem_grid))
            ] for i in range(len(problem_grid))
        ]

    def deep_copy_grid(grid: List[List]) -> List[List]:
        """
        Returns a deep copy of the grid argument.
        The reason why there is an empty grid and the a deep copy of a grid is the way python works with lists.
        For example, sample function and normal assignation of none to a list could modify the original list where
        it was defined from.
        By deep copying an empty grid we make sure, the original grid is not modified.
        Parameters:
            - grid (list)
        """

        return empty_grid(lambda i, j: grid[i][j])

    problem_grid = deep_copy_grid(problem_grid)

    def fitness(grid: List[List]) -> int:
        """
        Calculates the fitness function for a grid, the fitness integer is the number of repeated elements,
        either in a row, column or square.
        Parameters:
            - grid (list)
        Returns (int): The value of the fitness function for the input grid.
        """
        grid = np.array(grid)
        grid_2 = transform(grid) # Transforming

        ################# COUNT HOW MANY REPEATED NUMBERS ############################
        row = np.sum(9 - np.array([len(np.unique(r)) for r in grid_2]))
        column = np.sum(9 - np.array([len(np.unique(c)) for c in np.transpose(grid_2)]))
        square = np.sum(9 - np.array([len(np.unique(r)) for r in grid]))

        # Verification of given values
        actual = sum(x is not None for x in np.array(problem_grid).flatten()) - np.sum(np.array(problem_grid).flatten() == np.array(grid).flatten())
        fitness = row + column + square + actual
        return fitness

    def generate_initial_population(pop_size: int) -> List[List]:
        """
        Generates an initial population of size "population_size".
        Returns (list): An array of candidate grids.
        """

        candidates = []

        for k in range(pop_size):
            candidate = empty_grid()
            for i in range(len(problem_grid)):
                shuffled_sub_grid = [n for n in range(1, len(problem_grid) + 1)]
                shuffle(shuffled_sub_grid)

                for j in range(len(problem_grid)):
                    if problem_grid[i][j] is not None:
                        candidate[i][j] = problem_grid[i][j]

                        shuffled_sub_grid.remove(problem_grid[i][j])

                for j in range(len(problem_grid)):
                    if candidate[i][j] is None:
                        candidate[i][j] = shuffled_sub_grid.pop()

            candidates.append(candidate)

        return candidates

    def selection(candidates):
        """
        Returns the best portion ("selection_rate") of candidates based on their fitness function values (lower ones).
        Parameters:
          - candidates (list)
        Returns:
          - ordered candidates (list)
          - fitness of the first candidate (int)
          - fitness of the last candidate (int)
        """

        index_fitness = []
        for i in range(len(candidates)):
            index_fitness.append(tuple([i, fitness(candidates[i])]))
        index_fitness.sort(key=lambda elem: elem[1])

        selected_part = index_fitness[0: int(len(index_fitness) * selection_rate)]
        indexes = [e[0] for e in selected_part]

        return [candidates[i] for i in indexes], selected_part[0][1], selected_part[-1][1]

    population = generate_initial_population(population_size)
    best_fitness = 100 # initializing value with an improbable value
    fitness_history = [] # for plotting
    
    for i in range(max_generations_count):
        prev_fitness = best_fitness
        population, best_fitness, worst_fitness = selection(population) # selecting the best (selection_rate*population_size) candidates.
        if best_fitness == 0:  # If fitness equal to 0, then the solution is found.
            print(f"Generation {i} -Best candidate's fitness {best_fitness} -Worst candidate's fitness {worst_fitness}")
            break
        
        actual_pop_size = len(population)

        new_population_size = int((population_size - actual_pop_size) * (1 - random_proportion))
        random_population_size = int((population_size - actual_pop_size) * random_proportion)

        new_population = []

        #Cross-over
        for j in range(new_population_size):
            # Selecting two random candidates
            w1 = randint(0, actual_pop_size - 1)
            w2 = randint(0, actual_pop_size - 1)
            c1 = population[w1].copy() # Copy to avoid manipulating original list
            c2 = population[w2].copy()

            #Random cross-over
            cross_point = randint(0, 8)
            temp = c2[cross_point]
            c1[cross_point] = c2[cross_point] # Here we exchange a random row(That it was originally a square) from the first grid with another row from the second grid
            c2[cross_point] = temp

            if fitness(c1) < fitness(c2): # comparing best fitness of the two changes
                new_population.append(c1) # only appending the best candidate of the cross-over
            else:
                new_population.append(c2)

        random_population = generate_initial_population(random_population_size)

        # Mutation
        for candidate in new_population:
            if uniform(0, 1) < mutation_rate:
                random_sub_grid = randint(0, 8)
                possible_swaps = []
                for grid_element_index in range(len(problem_grid)):
                    if problem_grid[random_sub_grid][grid_element_index] is None:
                        possible_swaps.append(grid_element_index)
                if len(possible_swaps) > 1:
                    shuffle(possible_swaps)
                    first_index = possible_swaps.pop()
                    second_index = possible_swaps.pop()
                    tmp = candidate[random_sub_grid][first_index]
                    candidate[random_sub_grid][first_index] = candidate[random_sub_grid][second_index]
                    candidate[random_sub_grid][second_index] = tmp

        new_population = np.append(new_population, random_population, 0)

        population = np.append(population, new_population, 0)
        
        fitness_history.append(best_fitness)
        if verbose:
             print('Generation {} -Best candidate\'s fitness {} -Worst candidate\'s fitness {}'.format(i, best_fitness, worst_fitness)) # This is used to see progress in console of the solving

        # Resetting if local minimum
        if len(fitness_history) > 60 and len(np.unique(fitness_history[-49:])) == 1:
          print(population[0])
          population = generate_initial_population(population_size) # Create a whole new random population if last 20 fitness has not changed


        
    population, best_fitness, worst_fitness = selection(population)
    return population[0], best_fitness, fitness_history

# Solving

In [ ]:
solution, best_fitness, fit_history = solve(s, selection_rate=0.05, mutation_rate = 0.6, random_proportion=0.6, max_generations_count=200, verbose=False)

Generation 16 -Best candidate's fitness 0 -Worst candidate's fitness 2
